language: node_js
node_js:
  - "8.4"
services:
  - mongodb
sudo: false
cache:
  directories:
    - node_modules
    
before_install:
  - "npm install"
  
install:
  - npm install newman
  
before_script:
  - sleep 15

script:
  - node_modules/.bin/newman run tests/backend_server_tests.postman_collection.json -e tests/backend-tests.postman_environment.json
